# Generated by Powerlevel10k configuration wizard on 2026-01-10
# Customized: Catppuccin Mocha vivid + OS icon + bold dir/git + Nerd Font

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o aliases ]] || p10k_config_opts+=('aliases')
[[ ! -o sh_glob ]] || p10k_config_opts+=('sh_glob')
[[ ! -o no_brace_expand ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  ################################################################
  # Catppuccin Mocha (vivid)
  ################################################################
  local base='#CDD6F4'
  local sub='#A6ADC8'
  local red='#F38BA8'
  local peach='#FAB387'
  local yellow='#F9E2AF'
  local green='#A6E3A1'
  local teal='#94E2D5'
  local blue='#89B4FA'
  local mauve='#CBA6F7'

  local white=$base
  local grey=$sub
  local cyan=$teal
  local magenta=$mauve
  
  # Custom colors
  local skyblue='#87CEEB'  # Sky blue
  local orange='#FFA500'   # Orange

  ################################################################
  # OS icon (Nerd Font) - cached for performance
  ################################################################
  # Determine OS icon at config load time (only once, no function calls)
  # macOS: \uf179 (), Ubuntu: \uf31b (), Linux: \uf17c ()
  typeset -g _p10k_os_icon=''
  if [[ "$OSTYPE" == darwin* ]]; then
    _p10k_os_icon=$'\uf179'
  elif [[ -r /etc/os-release ]]; then
    # Read /etc/os-release only once at config load time
    local id=$(sed -n 's/^ID=//p' /etc/os-release 2>/dev/null | tr -d '"' | head -n1)
    local id_like=$(sed -n 's/^ID_LIKE=//p' /etc/os-release 2>/dev/null | tr -d '"' | head -n1)
    if [[ "$id" == ubuntu || "$id_like" == *ubuntu* || "$id_like" == *debian* ]]; then
      _p10k_os_icon=$'\uf31b'
    else
      _p10k_os_icon=$'\uf17c'
    fi
  else
    _p10k_os_icon=$'\uf17c'
  fi

  ################################################################
  # Prompt structure (Pure-like)
  ################################################################
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    context
    dir
    vcs
    command_execution_time
    newline
    virtualenv
    prompt_char
  )

  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    time
    newline
  )

  typeset -g POWERLEVEL9K_BACKGROUND=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false

  ################################################################
  # Prompt char
  ################################################################
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_FOREGROUND=$mauve
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND=$red
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=false

  ################################################################
  # Context (OS + user@host) - white
  ################################################################
  # Use cached icon variable directly (fastest, no function calls)
  # Username and hostname are commented out - only OS icon is shown
  typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_CONTENT_EXPANSION="${_p10k_os_icon}"
  # typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_CONTENT_EXPANSION="${_p10k_os_icon} %n@%m"  # Uncomment to show username@hostname
  typeset -g POWERLEVEL9K_CONTEXT_SUDO_CONTENT_EXPANSION="${_p10k_os_icon}"
  # typeset -g POWERLEVEL9K_CONTEXT_SUDO_CONTENT_EXPANSION="${_p10k_os_icon} %n@%m"  # Uncomment to show username@hostname
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_CONTENT_EXPANSION="${_p10k_os_icon}"
  # typeset -g POWERLEVEL9K_CONTEXT_ROOT_CONTENT_EXPANSION="${_p10k_os_icon} %n@%m"  # Uncomment to show username@hostname
  # White color for context (mac icon + username)
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=$white
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=$white

  ################################################################
  # Directory (bold, skyblue, Nerd Font folder icon)
  ################################################################
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=$skyblue
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=$skyblue
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=$skyblue
  # Make all directory segments bold
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  typeset -g POWERLEVEL9K_DIR_SHORTENED_BOLD=true
  # Use CONTENT_EXPANSION to wrap entire directory in bold
  typeset -g POWERLEVEL9K_DIR_CONTENT_EXPANSION='%B$P9K_CONTENT%b'

  ################################################################
  # Virtualenv
  ################################################################
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=$teal
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
  typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=

  ################################################################
  # Command execution time
  ################################################################
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=5
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$yellow

  ################################################################
  # Git (VCS) — bold & vivid
  ################################################################
  typeset -g POWERLEVEL9K_VCS_LOADING_TEXT=
  typeset -g POWERLEVEL9K_VCS_MAX_SYNC_LATENCY_SECONDS=0
  typeset -g POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind)

  # State colors - all orange for consistency
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$orange
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$orange
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$orange
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=$orange

  # Icons (Nerd Font) - git branch icon
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=$'\uf418'
  typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='@'
  typeset -g POWERLEVEL9K_VCS_DIRTY_ICON='*'
  typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=':⇣'
  typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=':⇡'
  typeset -g POWERLEVEL9K_VCS_{COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=1

  # Custom Git formatter to make text bold while keeping icons normal
  # Based on p10k-robbyrussell.zsh but with bold text
  function _p10k_vcs_bold_formatter() {
    emulate -L zsh
    if [[ -n $P9K_CONTENT ]]; then
      # If P9K_CONTENT is not empty, it's either "loading" or from vcs_info
      # Wrap text parts in bold but keep icons normal
      local content="$P9K_CONTENT"
      # Try to separate icon from text (icon is usually before first space)
      if [[ "$content" =~ '^([^ ]+)[ ](.+)$' ]]; then
        # Has icon and text separated by space
        typeset -g _p10k_vcs_format="${match[1]} %B${match[2]}%b"
      else
        # No space found, wrap everything in bold
        typeset -g _p10k_vcs_format="%B${content}%b"
      fi
    else
      # Use VCS_STATUS_* parameters for gitstatus plugin
      local icon=$'\uf418'
      local branch="${VCS_STATUS_LOCAL_BRANCH:-${VCS_STATUS_COMMIT[1,8]}}"
      local git_status=""  # Changed from 'status' to avoid conflict with zsh's read-only 'status' variable
      (( VCS_STATUS_NUM_CONFLICTED || VCS_STATUS_NUM_STAGED ||
         VCS_STATUS_NUM_UNSTAGED   || VCS_STATUS_NUM_UNTRACKED )) && git_status=" *"
      # Make branch name and status bold, keep icon normal
      typeset -g _p10k_vcs_format="${icon} %B${branch}${git_status}%b"
    fi
  }
  functions -M _p10k_vcs_bold_formatter 2>/dev/null || true

  # Disable default formatting and use custom formatter
  typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true
  typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='${$((_p10k_vcs_bold_formatter(1)))+${_p10k_vcs_format}}'
  typeset -g POWERLEVEL9K_VCS_LOADING_CONTENT_EXPANSION='${$((_p10k_vcs_bold_formatter(0)))+${_p10k_vcs_format}}'

  ################################################################
  # Time
  ################################################################
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=$sub
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%I:%M:%S %p}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

  ################################################################
  # Misc
  ################################################################
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  (( ! $+functions[p10k] )) || p10k reload
}

typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}
(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
